### ISSUE TITLE
Full path is returned when using `\` as directories separator

### ISSUE THREAD

**Issue by maicol07** [hailwood/idea-inertiajs-plugin#11]
**Bug description**  
If pages path uses `\` as directories separator instead of `/` the plugin returns the full path instead of the file name.

Example: `C:\Users\...\Documents\...\resources\js\Pages`

**To Reproduce**  
Change the path to use `\` (I don't think it works on Linux)

**Environment (please complete the following information):**

*   IDE & version: PHPStorm 2020.2.1
*   PHP version: 8.0
*   OS: Windows 11
*   Plugin version : 0.1.1
*   Laravel version: 8.55.0
*   Inertia.js composer version: 0.4.4
*   Inertia.js js version: 0.10.1
*   Typescript: No

**Comment by hailwood** [comment]
Hi @maicol07,

So just to confirm the issue here, if your pages are in the default location (resources/js/Pages) then it all works fine (although the placeholder in settings shows the slashes the wrong way).

But if you select a custom path then unless you manually switch the slashes around the other way, it doesn't work.
Is that what you're observing?

**Comment by maicol07** [comment]
No, the issue is simply with `\` in the path. For example:

*   Default location:
    *   `resources/js/Pages` works
    *   `resources\js\Pages` works, but returns full path

The same with a custom one:

*   `resources/js/MyPages` works
*   `resources\js\MyPages` works, but returns full path

**Comment by hailwood** [comment]
I'm still not entirely sure what you mean by returns the full path sorry,
Would you mind taking a screenshot of where you're seeing this path?

**Comment by maicol07** [comment]
*   Pages path set to: `C:/Users/Maicol/Documents/Progetti/Web/osm_rewrite/resources/js/Views`:
    *   Works without issues
![](https://user-images.githubusercontent.com/9463142/130201132-1abce944-42b2-446a-b7ad-82b5e292ba55.png)

*   Pages path set to: `C:\Users\Maicol\Documents\Progetti\Web\osm_rewrite\resources\js\Views`:
    *   Shows full paths:
![](https://user-images.githubusercontent.com/9463142/130201322-f1f98cbb-0d16-44a6-b705-5d9c830d54b9.png)

**Comment by hailwood** [comment]
Reproduced, thank you @maicol07,
I'll attempt to fix that tonight.

You can delete your images if you'd like (as I know you blanked the path earlier)

**Comment by maicol07** [comment]
> I'll attempt to fix that tonight.

Great!

> You can delete your images if you'd like (as I know you blanked the path earlier)

That's not an issue, I did that to focus more on the issue. Also the paths refers to an OSS project, so there isn't any problem :+1:

**Comment by hailwood** [comment]
Thanks @maicol07,

This should be fixed in 0.1.2 which has been submitted for review.
