### ISSUE TITLE
Support the Mithril adapter

### ISSUE THREAD

**Issue by maicol07** [hailwood/idea-inertiajs-plugin#6]
**Is your feature request related to a problem? Please describe.**
Currently, the plugin doesn't work with my [Mithril adapter](https://github.com/maicol07/inertia-mithril)

**Describe the solution you'd like**
Support my Mithril adapter

**Describe alternatives you've considered**
I've tried setting the path in settings but didn't work

**Comment by hailwood** [comment]
Hi @maicol07,

Thanks for giving the plugin a go :) Can you please expand on what's not working?

From what I can see Mithril is just standard JS files so should be supported out of the box.
I downloaded your pingcrm-mithril repository and it all appears to be working after updating the path in settings

Ctrl+Click support
![mithril](https://user-images.githubusercontent.com/709773/129681918-849b62a5-6453-420c-ace5-ea5a03d1d52a.png)

Go to usages support
![mithril](https://user-images.githubusercontent.com/709773/129682120-ad1edf68-f9e5-4b76-8eaa-aaaa35021229.png)

Autocomplete support
![mithril](https://user-images.githubusercontent.com/709773/129682255-4a5e9ccd-facc-49d9-bed0-ae27fcbe185a.png)

Settings used
![mithril](https://user-images.githubusercontent.com/709773/129682326-b6abc2dc-cb9d-4fac-801b-ebb78da7fe3f.png)



Cheers,
Matt

**Comment by maicol07** [comment]
@hailwood you are using the outdated Mithril adapter. I've forked the original one and updated it to the latest Inertia. With my fork none of the features of the plugin work

**Comment by hailwood** [comment]
Currently I don't actually check for what adapter we're using (I will eventually as I want to add a quick intention to create a missing page), so the adapter that it's using shouldn't really matter.

Can you please create a reproduction repository that I can download? Doesn't need to be complex, even just one Mithril page should be enough.

**Comment by maicol07** [comment]
@hailwood you can check the project I'm working on, since it's pretty empty at the moment: [Dasc3er/openstamanager@rewrite](https://github.com/Dasc3er/openstamanager/tree/rewrite)

**Comment by hailwood** [comment]
Ah I see,

I had forgotten `Route::inertia` was a thing.
I'll add support for that.
