### ISSUE TITLE
Support for PHPStorm 2022.3 EAP

### ISSUE THREAD

**Issue by trollfalgar** [hailwood/idea-inertiajs-plugin#75]
Please, update to support PHPStorm 2022.3 EAP.

**Comment by krekas** [comment]
@hailwood plugin abandoned?

**Comment by twdnhfr** [comment]
Any feedback? seems dead...

**Comment by medeiroz** [comment]
Any feedback? seems dead...

**Comment by hailwood** [comment]
Sorry folks, haven't had a lot of time for open source recently.

I'll look at pushing out an update in the next week to support the latest version of PHPStorm and the new Inertia 1.0 packages but I'll be honest - 
I'd suggest just using the Laravel Idea plugin as it does everything this plugin does, but way more effeciently (I learnt Kotlin to develop this plugin, so I'm not great with it) along with so much more for Laravel in general that makes it worth the comparatively small amount it costs. It's a big part of the reason this plugin is lagging behind, as I've just been using that.

I do understand though that Laravel Idea is a paid plugin so there will be some demand here still, if someone would like to take over this plugin I'd be open to handing over the keys.

**Comment by hailwood** [comment]
@medeiroz/@twdnhfr plugin version 0.1.7 is pending review now.
I've added support for the latest PHPstorm version and detection of Inertia projects based on the new inertia package names.

Reviews can take 1-2 days, In the meantime you should be able to manually download the update from https://plugins.jetbrains.com/plugin/17435-inertia-js-support/versions/stable/282277

**Comment by medeiroz** [comment]
> @medeiroz/@twdnhfr plugin version 0.1.7 is pending review now. I've added support for the latest PHPstorm version and detection of Inertia projects based on the new inertia package names.
> 
> Reviews can take 1-2 days, In the meantime you should be able to manually download the update from https://plugins.jetbrains.com/plugin/17435-inertia-js-support/versions/stable/282277

Awesome

**Comment by hailwood** [comment]
It's approved now :)
Should just update through the plugin manager

**Comment by hailwood** [comment]
LMAO, I'll release a version for the 2023.1 EAP line tonight.
